server:
  port: 9900
# Spring
spring:
  application:
    # 应用名称
    name: miles-system
  profiles:
    # 环境配置
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.server@
      discovery:
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml

