# 安全配置
security:
  # 防止XSS攻击
  xss:
    enabled: true
#    excludeUrls:
#      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /*/v3/api-docs
      - /*/error
#      - /csrf
      - /test/login

spring:
  cloud:
    # 网关配置
    gateway:
      # 打印请求日志(自定义)
      requestLog: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 系统模块
        - id: miles-system
          uri: lb://miles-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 测试模块
        - id: miles-test
          uri: lb://miles-test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
